"""
Main recognition pipeline integrating detection, embedding, recognition, and event logging.
"""
import time
import numpy as np
from datetime import datetime, timedelta
from typing import Optional, Callable, Dict
from dataclasses import dataclass
from threading import Thread, Event as ThreadEvent

from core.detector import FaceDetector, BBox
from core.embedder import FaceEmbedder
from core.recognizer import FaceRecognizer, RecognitionResult
from camera.capture import CameraInterface
from camera.frame_buffer import update as update_frame_buffer
from camera.photo import BestFrameSelector, PhotoStorage
from db.event_repo import EventRepository
from core.config import COOLDOWN_SECONDS


@dataclass
class PipelineEvent:
    """Event generated by the pipeline."""
    user_id: Optional[int]
    user_name: Optional[str]
    confidence: float
    is_known: bool
    photo_path: Optional[str]
    occurred_at: datetime
    bbox: Optional[BBox] = None


class Pipeline:
    """
    Main recognition pipeline.
    Continuously processes camera frames and triggers events.
    """

    def __init__(
        self,
        camera: CameraInterface,
        detector: FaceDetector,
        embedder: FaceEmbedder,
        recognizer: FaceRecognizer,
        event_repo: EventRepository,
        photo_storage: PhotoStorage,
        cooldown_seconds: int = COOLDOWN_SECONDS,
        on_event: Optional[Callable[[PipelineEvent], None]] = None
    ):
        """
        Initialize the pipeline.

        Args:
            camera: Camera interface
            detector: Face detector
            embedder: Face embedder
            recognizer: Face recognizer
            event_repo: Event repository
            photo_storage: Photo storage
            cooldown_seconds: Cooldown period to prevent duplicate logging
            on_event: Callback function for events (for notifications, live updates, etc.)
        """
        self.camera = camera
        self.detector = detector
        self.embedder = embedder
        self.recognizer = recognizer
        self.event_repo = event_repo
        self.photo_storage = photo_storage
        self.cooldown_seconds = cooldown_seconds
        self.on_event = on_event

        # Track last detection time per user/unknown to prevent duplicate logging
        self.last_seen: Dict[Optional[int], datetime] = {}

        # Best-frame collection for unknown visitors
        self.best_frame_selector: Optional[BestFrameSelector] = None
        self.collecting_frames_for: Optional[tuple] = None  # (embedding_hash, timestamp)

        # Threading
        self.running = False
        self.thread: Optional[Thread] = None
        self.stop_event = ThreadEvent()

        # Debug: count frames with zero faces to log periodic hint
        self._frames_without_faces = 0

        print("Pipeline initialized")

    def _hash_embedding(self, embedding: np.ndarray) -> int:
        """Create a hash of an embedding for tracking purposes."""
        # Use a subset of the embedding for hashing (faster)
        return hash(tuple(embedding[:32].astype(np.float16)))

    def _is_in_cooldown(self, user_id: Optional[int]) -> bool:
        """Check if a user is in cooldown period."""
        if user_id not in self.last_seen:
            return False

        elapsed = (datetime.now() - self.last_seen[user_id]).total_seconds()
        return elapsed < self.cooldown_seconds

    def _crop_face(self, frame: np.ndarray, bbox: BBox) -> np.ndarray:
        """Crop face from frame using bounding box."""
        return frame[bbox.y1:bbox.y2, bbox.x1:bbox.x2]

    def process_frame(self, frame: np.ndarray) -> list[PipelineEvent]:
        """
        Process a single frame.

        Args:
            frame: BGR image

        Returns:
            List of events generated (may be empty)
        """
        events = []

        # Detect faces
        bboxes = self.detector.detect(frame)

        if not bboxes:
            self._frames_without_faces += 1
            # No faces detected - reset frame collection if active
            if self.best_frame_selector is not None:
                self.best_frame_selector = None
                self.collecting_frames_for = None
            return events

        # Log when faces are detected (helps confirm pipeline is working)
        self._frames_without_faces = 0
        print(f"[Pipeline] Detected {len(bboxes)} face(s)")

        # Process each detected face
        for bbox in bboxes:
            # Crop face
            face_crop = self._crop_face(frame, bbox)

            if face_crop.size == 0:
                continue

            # Extract embedding
            embedding = self.embedder.embed(face_crop)

            if embedding is None:
                print("[Pipeline] Face detected but embedding failed (crop may be too small or invalid)")
                continue

            # Recognize
            result = self.recognizer.recognize(embedding)

            # Check cooldown
            if self._is_in_cooldown(result.user_id):
                continue

            # Handle based on recognition result
            if result.is_known:
                # Known user
                event = self._handle_known_user(result, bbox)
                if event:
                    events.append(event)
            else:
                # Unknown visitor
                event = self._handle_unknown_visitor(frame, bbox, embedding, result.confidence)
                if event:
                    events.append(event)

        return events

    def _handle_known_user(
        self,
        result: RecognitionResult,
        bbox: BBox
    ) -> Optional[PipelineEvent]:
        """
        Handle a known user detection.

        Args:
            result: Recognition result
            bbox: Face bounding box

        Returns:
            PipelineEvent if logged, None if skipped
        """
        # Log to database
        event_id = self.event_repo.log_event(
            user_id=result.user_id,
            confidence=result.confidence,
            photo_path=None
        )

        # Update last seen
        self.last_seen[result.user_id] = datetime.now()

        # Get user name
        from db.user_repo import UserRepository
        user_repo = UserRepository()
        user = user_repo.get_user(result.user_id)
        user_name = user.name if user else f"User {result.user_id}"

        # Create event
        event = PipelineEvent(
            user_id=result.user_id,
            user_name=user_name,
            confidence=result.confidence,
            is_known=True,
            photo_path=None,
            occurred_at=datetime.now(),
            bbox=bbox
        )

        print(f"✓ Recognized: {user_name} (confidence: {result.confidence:.2f})")

        # Trigger callback
        if self.on_event:
            self.on_event(event)

        return event

    def _handle_unknown_visitor(
        self,
        frame: np.ndarray,
        bbox: BBox,
        embedding: np.ndarray,
        confidence: float
    ) -> Optional[PipelineEvent]:
        """
        Handle an unknown visitor detection.
        Collects multiple frames and selects the best one.

        Args:
            frame: Full frame image
            bbox: Face bounding box
            embedding: Face embedding
            confidence: Recognition confidence (low for unknown)

        Returns:
            PipelineEvent if photo saved and logged, None if still collecting frames
        """
        emb_hash = self._hash_embedding(embedding)

        # Check if this is the same unknown visitor we're already collecting frames for
        if self.best_frame_selector is not None:
            if self.collecting_frames_for and self.collecting_frames_for[0] == emb_hash:
                # Same visitor, add frame
                self.best_frame_selector.add(frame, confidence)

                if self.best_frame_selector.is_full():
                    # We have enough frames, select best and save
                    return self._finalize_unknown_visitor(confidence)
                else:
                    # Still collecting
                    return None
            else:
                # Different visitor appeared, finalize previous one
                prev_event = self._finalize_unknown_visitor(confidence)
                # Start new collection
                self.best_frame_selector = BestFrameSelector()
                self.best_frame_selector.add(frame, confidence)
                self.collecting_frames_for = (emb_hash, datetime.now())
                return prev_event
        else:
            # Start new frame collection
            self.best_frame_selector = BestFrameSelector()
            self.best_frame_selector.add(frame, confidence)
            self.collecting_frames_for = (emb_hash, datetime.now())
            return None

    def _finalize_unknown_visitor(self, confidence: float) -> Optional[PipelineEvent]:
        """
        Finalize unknown visitor detection by saving the best frame and logging event.

        Args:
            confidence: Recognition confidence

        Returns:
            PipelineEvent if successful, None otherwise
        """
        if self.best_frame_selector is None:
            return None

        # Select best frame
        best_frame = self.best_frame_selector.select()

        if best_frame is None:
            self.best_frame_selector = None
            self.collecting_frames_for = None
            return None

        # Save photo
        try:
            photo_path, _ = self.photo_storage.save_photo(best_frame, confidence)
        except Exception as e:
            print(f"Error saving photo: {e}")
            self.best_frame_selector = None
            self.collecting_frames_for = None
            return None

        # Log to database
        event_id = self.event_repo.log_event(
            user_id=None,
            confidence=confidence,
            photo_path=photo_path
        )

        # Update last seen for unknown visitors (use None as key)
        self.last_seen[None] = datetime.now()

        # Create event
        event = PipelineEvent(
            user_id=None,
            user_name="Unknown",
            confidence=confidence,
            is_known=False,
            photo_path=photo_path,
            occurred_at=datetime.now()
        )

        print(f"⚠ Unknown visitor detected (confidence: {confidence:.2f}, photo: {photo_path})")

        # Trigger callback
        if self.on_event:
            self.on_event(event)

        # Reset frame collection
        self.best_frame_selector = None
        self.collecting_frames_for = None

        return event

    def run_once(self) -> list[PipelineEvent]:
        """
        Process a single frame from the camera.

        Returns:
            List of events generated
        """
        frame = self.camera.read()

        if frame is None:
            return []

        update_frame_buffer(frame)
        return self.process_frame(frame)

    def run(self):
        """
        Run the pipeline continuously.
        Processes frames until stopped.
        """
        self.running = True
        self.stop_event.clear()

        print("Pipeline started")

        frame_count = 0
        start_time = time.time()

        try:
            while self.running and not self.stop_event.is_set():
                events = self.run_once()
                frame_count += 1

                # Print FPS and detection hint every 100 frames
                if frame_count % 100 == 0:
                    elapsed = time.time() - start_time
                    fps = frame_count / elapsed
                    print(f"Pipeline FPS: {fps:.1f}")
                # Hint every 500 frames if no face was ever detected
                if frame_count % 500 == 0 and frame_count > 0 and self._frames_without_faces >= 500:
                    print(
                        "[Pipeline] No faces detected in last 500 frames. "
                        "If you see a face on the live feed, try lowering DETECTION_THRESHOLD "
                        "(e.g. 0.5) in .env"
                    )

                # Small sleep to prevent CPU spinning if camera is slow
                time.sleep(0.001)

        except KeyboardInterrupt:
            print("\nPipeline interrupted by user")
        except Exception as e:
            print(f"Pipeline error: {e}")
            import traceback
            traceback.print_exc()
        finally:
            self.running = False
            print("Pipeline stopped")

    def start_async(self):
        """Start the pipeline in a background thread."""
        if self.thread is not None and self.thread.is_alive():
            print("Pipeline already running")
            return

        self.thread = Thread(target=self.run, daemon=True)
        self.thread.start()
        print("Pipeline started in background thread")

    def stop(self):
        """Stop the pipeline."""
        self.running = False
        self.stop_event.set()

        if self.thread is not None:
            self.thread.join(timeout=5.0)
            self.thread = None

        print("Pipeline stopped")
